apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-2
  namespace: simple-k8s
  labels:
    app: hello-world-2
    app.kubernetes.io/managed-by: simple-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-2
  template:
    metadata:
      labels:
        app: hello-world-2
        app.kubernetes.io/managed-by: simple-k8s
    spec:
      containers:
        - name: hello-world-2
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
          env: []
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-2
  namespace: simple-k8s
  labels:
    app: hello-world-2
    app.kubernetes.io/managed-by: simple-k8s
spec:
  selector:
    app: hello-world-2
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-2
  namespace: simple-k8s
  labels:
    app: hello-world-2
    app.kubernetes.io/managed-by: simple-k8s
spec:
  rules:
    - host: hello.aevy.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-2
                port:
                  number: 80
