apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowo
  namespace: simple-k8s
  annotations:
    simple-k8s/display-name: "Hello World"
  labels:
    app: hellowo
    app.kubernetes.io/managed-by: simple-k8s
spec:
  selector:
    matchLabels:
      app: hellowo
  template:
    metadata:
      labels:
        app: hellowo
        app.kubernetes.io/managed-by: simple-k8s
    spec:
      containers:
        - name: hellowo
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
          env: []
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hellowo
  namespace: simple-k8s
  labels:
    app: hellowo
    app.kubernetes.io/managed-by: simple-k8s
spec:
  selector:
    app: hellowo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellowo
  namespace: simple-k8s
  labels:
    app: hellowo
    app.kubernetes.io/managed-by: simple-k8s
spec:
  rules:
    - host: hello2.aevy.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hellowo
                port:
                  number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hellowo
  namespace: simple-k8s
  labels:
    app: hellowo
    app.kubernetes.io/managed-by: simple-k8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hellowo
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
